global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'PRODUCT-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.100.62:9008']
        labels:
          application: 'Product Service Application'
  - job_name: 'ORDER-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.100.62:9009']
        labels:
          application: 'Order Service Application'